// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcMyV0YnSKIdJC8p8j9fy62dabQA2l85g',
    appId: '1:677343660707:web:9b81b934b23ba31d04cd16',
    messagingSenderId: '677343660707',
    projectId: 'hydrosense-3f591',
    authDomain: 'hydrosense-3f591.firebaseapp.com',
    databaseURL: 'https://hydrosense-3f591-default-rtdb.firebaseio.com',
    storageBucket: 'hydrosense-3f591.firebasestorage.app',
    measurementId: 'G-YKYGNP5FPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC37OHPmO89lRBuRcgEkChVUJjOI4vZreI',
    appId: '1:677343660707:android:5c1de83605074c1f04cd16',
    messagingSenderId: '677343660707',
    projectId: 'hydrosense-3f591',
    databaseURL: 'https://hydrosense-3f591-default-rtdb.firebaseio.com',
    storageBucket: 'hydrosense-3f591.firebasestorage.app',
  );
}
